const d=document.querySelector('#calcDisplay');let expr='';
function normalize(e){return e.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll('^','**').replaceAll('√','Math.sqrt');}
document.querySelectorAll('[data-calc]').forEach(b=>b.onclick=()=>{const x=b.dataset.calc;if(x==='C'){expr='';d.value='';return}if(x==='⌫'){expr=expr.slice(0,-1);d.value=expr;return}if(x==='='){try{let e=normalize(expr).replace(/(\d+(?:\.\d+)?)²/g,'($1**2)').replace(/(\d+(?:\.\d+)?)%/g,'($1/100)').replace(/(\d+(?:\.\d+)?)1\/x/g,'(1/$1)');e=e.replace(/sin\(/g,'Math.sin(').replace(/cos\(/g,'Math.cos(').replace(/tan\(/g,'Math.tan(');const val=Function('return '+e)();d.value=Number.isFinite(val)?Number(val.toFixed(12)): 'خطأ';expr=d.value; }catch{d.value='خطأ';expr=''}return}if(x==='x²'){expr+='²'}else if(x==='1/x'){expr+='1/x'}else if(x==='√'){expr+='√'}else expr+=x;d.value=expr});
const units={length:{'متر':1,'سنتيمتر':.01,'كيلومتر':1000,'مليمتر':.001,'ميل':1609.344,'ياردة':.9144,'قدم':.3048,'بوصة':.0254},area:{'م²':1,'كم²':1e6,'سم²':.0001,'هكتار':10000,'فدان':4046.856422},volume:{'لتر':1,'مليلتر':.001,'م³':1000,'سم³':.001,'جالون أمريكي':3.785411784},weight:{'كيلوغرام':1,'غرام':.001,'مليغرام':1e-6,'طن':1000,'رطل':.45359237,'أونصة':.0283495231},speed:{'م/ث':1,'كم/س':1/3.6,'ميل/س':.44704,'عقدة':.514444},time:{'ثانية':1,'دقيقة':60,'ساعة':3600,'يوم':86400,'أسبوع':604800},data:{'بايت':1,'كيلوبايت':1024,'ميغابايت':1048576,'غيغابايت':1073741824,'تيرابايت':1099511627776}};
const cats={length:'الطول',area:'المساحة',volume:'الحجم',weight:'الوزن',speed:'السرعة',temp:'الحرارة',time:'الوقت',data:'البيانات الرقمية'};const cat=document.querySelector('#unitCategory'),from=document.querySelector('#fromUnit'),to=document.querySelector('#toUnit'),ui=document.querySelector('#unitInput'),ur=document.querySelector('#unitResult');
function fillUnits(){const c=cat.value;if(c==='temp'){from.innerHTML='<option>مئوية</option><option>فهرنهايت</option><option>كلفن</option>';to.innerHTML='<option>فهرنهايت</option><option>مئوية</option><option>كلفن</option>'}else{const names=Object.keys(units[c]);from.innerHTML=names.map(x=>'<option>'+x+'</option>').join('');to.innerHTML=names.map(x=>'<option>'+x+'</option>').join('')}convert()}
function convert(){const v=Number(ui.value);if(ui.value===''||Number.isNaN(v)){ur.textContent='—';return}let r;if(cat.value==='temp'){const f=from.value,t=to.value;let c=f==='مئوية'?v:f==='فهرنهايت'?(v-32)*5/9:v-273.15;r=t==='مئوية'?c:t==='فهرنهايت'?c*9/5+32:c+273.15}else{const base=v*units[cat.value][from.value];r=base/units[cat.value][to.value]}ur.textContent=Number(r.toFixed(8)).toLocaleString('ar-SA')}
cat.onchange=fillUnits;from.onchange=convert;to.onchange=convert;ui.oninput=convert;fillUnits();
let seconds=300,interval=null;const td=document.querySelector('#timerDisplay');function show(){const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;td.textContent=[h,m,s].map(n=>String(n).padStart(2,'0')).join(':')}function setTimer(){seconds=Number(document.querySelector('#hours').value||0)*3600+Number(document.querySelector('#minutes').value||0)*60+Number(document.querySelector('#seconds').value||0);show()}['hours','minutes','seconds'].forEach(id=>document.querySelector('#'+id).oninput=setTimer);document.querySelector('#startTimer').onclick=()=>{if(interval)return;interval=setInterval(()=>{if(seconds<=0){clearInterval(interval);interval=null;return}seconds--;show()},1000)};document.querySelector('#pauseTimer').onclick=()=>{clearInterval(interval);interval=null};document.querySelector('#resetTimer').onclick=()=>{clearInterval(interval);interval=null;setTimer()};show();
const color=document.querySelector('#color'),hex=document.querySelector('#hex'),rgb=document.querySelector('#rgb');color.oninput=()=>{hex.textContent=color.value.toUpperCase();const n=parseInt(color.value.slice(1),16);rgb.textContent='RGB('+((n>>16)&255)+', '+((n>>8)&255)+', '+(n&255)+')'};
const textInput=document.querySelector('#textInput');textInput.oninput=()=>{const t=textInput.value.trim();document.querySelector('#words').textContent=t?t.split(/\s+/).length:0;document.querySelector('#chars').textContent=textInput.value.length};
const out=document.querySelector('#passwordOutput');document.querySelector('#generate').onclick=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';out.value=Array.from({length:16},()=>chars[Math.floor(Math.random()*chars.length)]).join('')};